# Generated by Django 3.2.3 on 2021-05-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_auto_20210526_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('descripcio', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Formacio',
                'verbose_name_plural': 'Formacions',
                'default_permissions': {'view', 'add', 'delete', 'change'},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciat', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntes',
                'default_permissions': {'view', 'add', 'delete', 'change'},
            },
        ),
        migrations.CreateModel(
            name='Pregunta_Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacions.pregunta')),
            ],
            options={
                'verbose_name': 'Relacio Pregunta-Resposta',
                'verbose_name_plural': 'Relacions Pregunta-Resposta',
                'default_permissions': {'view', 'add', 'delete', 'change'},
            },
        ),
        migrations.CreateModel(
            name='Formacio_Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacions.formacio')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacions.pregunta')),
            ],
            options={
                'verbose_name': 'Relacio Formacio-Pregunta',
                'verbose_name_plural': 'Relacions Formacio-Pregunta',
                'default_permissions': {'view', 'add', 'delete', 'change'},
            },
        ),
        migrations.CreateModel(
            name='Formacio_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.empresa')),
                ('formacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacions.formacio')),
            ],
            options={
                'verbose_name': 'Relacio Formacio-Empresa',
                'verbose_name_plural': 'Relacions Formacio-Empresa',
                'default_permissions': {'view', 'add', 'delete', 'change'},
            },
        ),
    ]
