# Generated by Django 3.2.3 on 2021-05-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacio',
            name='descripcio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='enunciat',
            field=models.TextField(),
        ),
    ]
