# Generated by Django 3.2.3 on 2021-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacions', '0002_auto_20210526_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta_resposta',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta_resposta',
            name='resposta',
            field=models.TextField(),
        ),
    ]
