# Generated by Django 3.2.3 on 2021-06-02 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formacions', '0003_auto_20210531_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacio_Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacio', models.IntegerField(blank=True, default=0, null=True)),
                ('data_ultima_realitzacio', models.DateField(blank=True, null=True)),
                ('formacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacions.formacio')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relacio Formacio realitzada-Usuari',
                'verbose_name_plural': 'Relacions Formacions realitzades-Usuaris',
                'default_permissions': {'add', 'view', 'delete', 'change'},
            },
        ),
    ]
