# Generated by Django 3.2.3 on 2021-06-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacions', '0004_formacio_usuari'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacio_usuari',
            name='max_puntuacio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
