# Generated by Django 3.2.3 on 2021-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210519_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'default_permissions': {'change', 'view', 'delete', 'add'}, 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empreses'},
        ),
        migrations.AlterModelOptions(
            name='usuari',
            options={'default_permissions': {'change', 'view', 'delete', 'add'}, 'verbose_name': 'Usuari', 'verbose_name_plural': 'Usuari'},
        ),
        migrations.AlterField(
            model_name='usuari',
            name='if_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
