# Generated by Django 3.2.3 on 2021-06-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usuari_puntuacio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuari',
            old_name='puntuacio',
            new_name='puntuacio_actual',
        ),
        migrations.AddField(
            model_name='usuari',
            name='max_puntuacio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
