# Generated by Django 3.2.3 on 2021-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210608_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuari',
            old_name='max_puntuacio',
            new_name='max_puntuacio_actual',
        ),
        migrations.AddField(
            model_name='usuari',
            name='max_puntuacio_acumulada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuari',
            name='puntuacio_acumulada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
