# Generated by Django 3.2.3 on 2021-06-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210608_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='max_puntuacio_actual',
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='puntuacio_actual',
        ),
    ]
