# Generated by Django 3.2.3 on 2021-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210608_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='formacions_acumulades',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
